services:
  frontend:
    volumes:
      - ./frontend/:/app/
    user: "${UID}:${GID}"
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"
  backend:
    volumes:
      - ./backend/:/app/
    user: "${UID}:${GID}"
    environment:
      PYTHONUNBUFFERED: "1"
      HOME: "/app"
    command: >-
      sh -c "pip install --user -e . &&
             python -m babel.messages.frontend compile -d app/locales &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
