version: '3'

vars:
  LOCALES_DIR: "app/locales"
  TRANSLATION_LANGUAGES: ["en", "fr"]
  TRANSLATION_SOURCE_DIRS: ["app/api", "app/business"]

tasks:
  run-server:
    desc: "Run the uvicorn server"
    cmds:
      - uv run uvicorn app.main:app --reload

  tests:
    desc: "Run the tests"
    cmds:
      - uv run tox -vv

  translations-extract:
    desc: "Extract translatable strings from Python files into a .pot template"
    cmds:
      - >
        pybabel extract -F babel.cfg 
        -o {{ .LOCALES_DIR }}/messages.pot 
        --no-location
        --project="Suffering Footprint"
        --version="0.1.0" 
        {{ .TRANSLATION_SOURCE_DIRS | join " " }}
      - echo "✅ All strings extracted with Babel!"
    silent: true

  translations-update:
    desc: "Update .po files for all languages"
    cmds:
      - |
        for lang in {{ .TRANSLATION_LANGUAGES | join " " }}; do
          mkdir -p {{ .LOCALES_DIR }}/$lang/LC_MESSAGES
          if [ -f {{ .LOCALES_DIR }}/$lang/LC_MESSAGES/messages.po ]; then
              pybabel update -i {{ .LOCALES_DIR }}/messages.pot -d {{ .LOCALES_DIR }} -l $lang
          else
            pybabel init -i {{ .LOCALES_DIR }}/messages.pot -d {{ .LOCALES_DIR }} -l $lang
          fi
        done
      - echo "✅ All .po files updated with Babel!"
    silent: true

  translations-compile:
    desc: "Compile .po files into .mo files"
    cmds:
      - pybabel compile -d {{ .LOCALES_DIR }}
      - echo "✅ All .mo files compiled with Babel!"
    silent: true

  translations-all:
    desc: "Run all tasks: extract, update, and compile"
    cmds:
      - task: translations-extract
      - task: translations-update
      - task: translations-compile
