import re
import unicodedata


class ProductTypePatternRepository:
    FRESH_CHICKEN_EGG_TAGS = {
        "en:fresh-eggs",
        "en:chicken-eggs",
    }

    FRESH_EGG_TERMS = {"fresh", "frais", "freschi", "fresco"}

    CHICKEN_EGG_TERMS = {"poule", "chicken", "hen", "gallina", "pollo"}

    EXCLUDED_CATEGORY_TAGS = {
        "en:egg-yolk",
        "en:boiled-eggs",
        "en:hard-boiled-egg",
        "en:pickled-eggs",
        "en:quail-eggs",
        "en:duck-eggs",
        "en:goose-eggs",
        "en:ostrich-eggs",
        "en:turkey-eggs",
        "en:pheasant-eggs",
        "en:emu-eggs",
        "en:guineafowl-eggs",
        "en:gull-eggs",
        "en:scotch-eggs",
        "en:meals",
        "en:snacks",
        "en:meats-and-their-products",
        "en:festive-foods",
        "en:cocoa-and-its-products",
        "en:sweet-snacks",
        "en:easter-food",
        "en:easter-eggs",
        "en:chocolate-eggs",
        "en:meats",
        "en:cereals-and-potatoes",
        "fr:ovo-produits",
        "en:desserts",
    }

    EXCLUDED_WORDS = {
        "a la russe",
        "acidule?",
        "after",
        "angelina",
        "assaisonnement",
        "assortis?",
        "aux oeufs",
        "avec",
        "bacon",
        "baguette",
        "barre",
        "biscuits?",
        "blancs d oeufs?",
        "boiled",
        "bonbons?",
        "boudoirs",
        "bowl",
        "brioches?",
        "brouillade",
        "brouille",
        "brouilles",
        "bunny",
        "cabillauds?",
        "cacao",
        "cacher",
        "cadbury",
        "cailles?",
        "canard",
        "capelan",
        "caramel",
        "cent ans",
        "cheese",
        "choco",
        "chocolate?s?",
        "circus",
        "cloche",
        "clochettes?",
        "colour(ed)?",
        "comte",
        "coquillettes?",
        "coquilles",
        "cookies",
        "cooked",
        "craquant",
        "crackers?",
        "cremes?",
        "crepes?",
        "croco",
        "crudites?",
        "croustillant",
        "croustillants?",
        "cuillers?",
        "cuits?",
        "cuit",
        "curry",
        "degustation",
        "dessert",
        "dino",
        "dinosaures?",
        "dip",
        "dippy",
        "dragees?",
        "drageifie",
        "duck",
        "durs?",
        "eafit",
        "easter",
        "eclats?",
        "egg white",
        "egg whites?",
        "eggwhite",
        "emu",
        "epinards",
        "entiers?",
        "faberge",
        "falize",
        "farfalles?",
        "ferrero",
        "feuillete",
        "filled",
        "finettes?",
        "fish",
        "flamme",
        "flan",
        "florentine",
        "fourre",
        "fourres",
        "fried",
        "fleurs?",
        "fun",
        "funny?",
        "garni",
        "gateaux?",
        "gaufres?",
        "geant",
        "gelee",
        "genoises?",
        "gnocchis?",
        "gorgonzola",
        "gourmands?",
        "gourmet",
        "goose",
        "guineafowl",
        "gull",
        "hunt",
        "icelandic",
        "jam",
        "jambon",
        "jaune d",
        "jardin",
        "jazzy",
        "jelly",
        "julienne",
        "kinder",
        "kitkat",
        "knepfle",
        "lactes",
        "lapin",
        "lasagnes?",
        "lait",
        "lentilles",
        "ligne",
        "liqueur",
        "liquides?",
        "liquid",
        "liquido",
        "liquida",
        "lindor",
        "lompes?",
        "loprofin",
        "lump",
        "lympe",
        "madeleine",
        "madeleines?",
        "magiques?",
        "marbré?",
        "mars",
        "marzipan",
        "mascarpone",
        "mayonn?aise",
        "mafaldine",
        "mayo",
        "m ms?",
        "meat",
        "mendiants?",
        "milka",
        "mini",
        "mimosas?",
        "milk",
        "mollets?",
        "mouettes?",
        "moulage",
        "muges",
        "naproxene",
        "neiges?",
        "nids?",
        "noir",
        "noisettes?",
        "noodles?",
        "nougat",
        "nougatines?",
        "nouilles?",
        "onion",
        "oreo",
        "orgran",
        "ostrich",
        "paques?",
        "pain",
        "panzani",
        "papillons",
        "pastes?",
        "pasteurise??",
        "pastas?",
        "patissier",
        "pates?",
        "pate",
        "patisserie",
        "pavot",
        "peeled",
        "penne",
        "pickled",
        "pheasant",
        "poche?",
        "pokemon",
        "pomme",
        "poached",
        "poisson",
        "poulet",
        "poussin",
        "prednisolone",
        "preema",
        "printemps",
        "praline?",
        "pralines?",
        "quail",
        "quarts",
        "quatre quarts",
        "quatrequarts",
        "quenelles",
        "ravioli",
        "ravioles?",
        "reese",
        "rice",
        "riz",
        "rocket",
        "rolls?",
        "rouge",
        "rubans?",
        "rustic",
        "saumons?",
        "sachet",
        "salades?",
        "salted",
        "sando",
        "sandwich",
        "saumon",
        "sausage",
        "savoureux",
        "scotch",
        "scrambled?",
        "servis",
        "smarties",
        "snack",
        "sonic",
        "spaetzle",
        "spaghetti",
        "spatzle",
        "speckled",
        "substitute",
        "substitut",
        "sucres?",
        "sucrés",
        "surprises?",
        "sweet",
        "taipei",
        "tagliatelles?",
        "tarallis?",
        "tartes?",
        "tendres?",
        "thon",
        "toblerone",
        "tomates?",
        "tortellini",
        "torsades?",
        "touron",
        "truites?",
        "truffes?",
        "turkey",
        "valeur",
        "vegan",
        "vichy",
        "waitrose",
        "waffles?",
        "wraps?",
        "yolk",
    }

    EXCLUDED_PATTERNS = re.compile(
        r"\b(" + r"|".join([term.replace(" ", r"\s+") for term in EXCLUDED_WORDS]) + r")\b", re.VERBOSE
    )

    @staticmethod
    def clean(s: str | None) -> str:
        """
        Cleans a string by removing accents, replacing punctuation and digits,
        converting to lowercase, and replacing 'œ' with 'oe' before regex matching.
        Args:     s (str | None): The string to clean.

        Returns:  str: The cleaned string.
        """
        if not s:
            return ""
        s = s.lower().replace("œ", "oe")
        s = unicodedata.normalize("NFD", s)
        s = "".join(c for c in s if unicodedata.category(c) != "Mn")
        s = re.sub(r"[^\w\s]|\d+", " ", s)
        return s
