import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/ui/general/navbar";
import Head from "next/head";
import React from "react";
import SkipLink from "./components/SkipLink";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title></title>
      </Head>

      <SkipLink />

      <body className={`antialiased`}>
        <header>
          <div className="fixed w-full flex-none">
            <Navbar />
          </div>
        </header>
        <main id="main">{children}</main>
      </body>
    </html>
  );
}
