model:
  name: minishlab/potion-base-8M
dataset:
  full_ocr:
    path: data/ocr_elevage.csv
    X_col: ocr_text
  span_ocr:
    path: data/ocr_groq_spans_elevage.csv
    X_col: breeding_type_related
  synth_ocr:
    path: data/synthetic_barn_ocr.csv
    X_col: ocr_text

  train_test_split: 0.15
  y_col: elevage

evaluation:
  k_fold: 5
