name: Backend tests

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies with UV
        run: uv sync --all-groups

      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Compile translations
        run: |
          for po in app/locales/*/LC_MESSAGES/messages.po; do
            msgfmt --output-file=${po%.po}.mo $po
          done

      - name: Run tests
        run: uv run pytest tests/
