name: Frontend tests

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run type-check

      - name: Run unit tests (Jest)
        run: npm run test
        
      - name: Build app
        run: npm run build
